import type { Repo, StatusResponse, Worktree } from "../src/types";
export const repo: Repo = {
  id: "test",
  label: "Test project",
  path: "/test",
  excludedBranches: [],
};
export const primary: Worktree = {
  branch: "main",
  path: "/test",
  primary: true,
  state: "DIRTY-PRIMARY",
  dirty: 1,
  ahead: 0,
  behind: 0,
  upstream: "origin/main",
  headSha: "a".repeat(40),
  lastCommit: "abc Base commit",
  changedFiles: ["notes.txt"],
  isDirty: true,
  merged: true,
  preview: null,
  category: "attention",
  reason: "The primary checkout has local changes.",
  nextAction: "Identify who owns these changes before starting new work.",
  overlappingFiles: [],
  checks: "not-run",
};
export const ready: Worktree = {
  ...primary,
  primary: false,
  branch: "codex/ready",
  state: "COMPLETE",
  dirty: 0,
  isDirty: false,
  merged: false,
  category: "ready",
  reason: "Clean merge preview; no shared files.",
  nextAction: "Review and test before merging.",
  preview: {
    branch: "codex/ready",
    headSha: "a".repeat(40),
    baseSha: "b".repeat(40),
    baseRef: "refs/remotes/origin/main",
    checkedAt: new Date().toISOString(),
    files: [],
    outcome: "clean",
    message: "Git can combine these commits.",
  },
};
export function response(): StatusResponse {
  return {
    repoId: "test",
    error: null,
    refreshing: false,
    stale: false,
    status: {
      repoId: "test",
      label: "Test project",
      baseRef: "refs/remotes/origin/main",
      baseSha: "b".repeat(40),
      generatedAt: new Date().toISOString(),
      durationMs: 900,
      incomplete: false,
      worktrees: [primary, ready],
      conflicts: [],
      fileMapSize: 1,
    },
    worker: {
      enabled: false,
      status: "paused",
      heartbeat: new Date().toISOString(),
      lastRun: null,
      error: null,
    },
    history: [],
    taskContexts: [],
  };
}
