import { writeFile, mkdir } from "node:fs/promises";
import openapiTS, { astToString } from "openapi-typescript";
import { contract } from "../server/contract.mjs";

await mkdir("docs", { recursive: true });
await writeFile("docs/openapi.json", `${JSON.stringify(contract, null, 2)}\n`);
await writeFile(
  "src/api.generated.ts",
  `// Generated by npm run generate:api. Edit server/contract.mjs.\n${astToString(await openapiTS(contract))}`,
);
